### ISSUE TITLE
Mismatch between role tags and supported platforms

### ISSUE THREAD

**Issue by goetzk** [tschifftner/ansible-role-duplicity#3]
Hi,
I just noticed your role tags and description only mention Debian systems, but RHEL and Fedora are mentioned in supported platforms.
A quick look at the source code suggests the description/tags are out of date; is that the case?

**Comment by tschifftner** [comment]
Redhat support was added by @f-andrey. This might still work but was not tested lately.

**Comment by f-andrey** [comment]
Thanks for the reminder, I'll check it in the near future and try to fix it if something does not work, after the last commits

**Comment by goetzk** [comment]
thanks guys!
