### ISSUE TITLE
GPG encryption support

### ISSUE THREAD

**Issue by goetzk** [tschifftner/ansible-role-duplicity#5]
Hi @tschifftner ,
I'm looking at adding GPG key generating support to this role. Is that something you would consider merging or should I be planning to maintain it separately?

thanks,
Karl.

**Comment by tschifftner** [comment]
Hi Karl, I am willing to merge Pull Requests. But this role is not maintained anymore so you might be better off maintaining it separately.

**Comment by goetzk** [comment]
Thanks for the quick response - I will be working on this on and off for the next month and will try to produce mergable changesets. 
If I end up creating too much of a mess I'll keep my changes separate!

thanks,
Karl.

**Comment by goetzk** [comment]
Hi Tobias,
I've been looking at the role today and I keep coming across things which need changing (python2 -> 3 is staring me in the face now) and because of that I don't think my changes will be sensibly restricted to those related to GPG and I'm likely to end up with a much larger changeset.

I suspect that I will end up with a substantially forked version of the role which can't be merged (without substantial functionality changes) when I'm done so I suggest we close this issue.

Thanks for leaving the role available for me to reference and being a responsive upstream!

Karl.
